<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Xingyi Andrew, Si Miao and Zhiyuan Ren" />


<title>Project AAPL</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Forecasting Using Trend and Seasonality</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="Project-AAPL.html">Project AAPL</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Project AAPL</h1>
<h4 class="author">Xingyi Andrew, Si Miao and Zhiyuan Ren</h4>
<h4 class="date">4/22/2020</h4>

</div>


<div id="load-libraries" class="section level1">
<h1>Load Libraries</h1>
<pre class="r"><code>library(&quot;fImport&quot;)</code></pre>
<pre><code>## Loading required package: timeDate</code></pre>
<pre><code>## Loading required package: timeSeries</code></pre>
<pre class="r"><code>library(RQuantLib)</code></pre>
<pre><code>## Sufficient QuantLib version with insufficient configuration.</code></pre>
<pre><code>## Try configuring your build with the --enable-intraday argument.</code></pre>
<pre><code>## 
## Attaching package: &#39;RQuantLib&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:timeDate&#39;:
## 
##     isHoliday, isWeekend</code></pre>
<pre class="r"><code>library(nlstools)</code></pre>
<pre><code>## 
## &#39;nlstools&#39; has been loaded.</code></pre>
<pre><code>## IMPORTANT NOTICE: Most nonlinear regression models and data set examples</code></pre>
<pre><code>## related to predictive microbiolgy have been moved to the package &#39;nlsMicrobio&#39;</code></pre>
<pre class="r"><code>library(tseries)</code></pre>
<pre><code>## Registered S3 method overwritten by &#39;quantmod&#39;:
##   method            from
##   as.zoo.data.frame zoo</code></pre>
<pre><code>## 
##     &#39;tseries&#39; version: 0.10-47
## 
##     &#39;tseries&#39; is a package for time series analysis and
##     computational finance.
## 
##     See &#39;library(help=&quot;tseries&quot;)&#39; for details.</code></pre>
<pre class="r"><code>library(Quandl)</code></pre>
<pre><code>## Loading required package: xts</code></pre>
<pre><code>## Loading required package: zoo</code></pre>
<pre><code>## 
## Attaching package: &#39;zoo&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:timeSeries&#39;:
## 
##     time&lt;-</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     as.Date, as.Date.numeric</code></pre>
<pre class="r"><code>library(zoo)
library(PerformanceAnalytics)</code></pre>
<pre><code>## 
## Attaching package: &#39;PerformanceAnalytics&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:timeDate&#39;:
## 
##     kurtosis, skewness</code></pre>
<pre><code>## The following object is masked from &#39;package:graphics&#39;:
## 
##     legend</code></pre>
<pre class="r"><code>library(quantmod)</code></pre>
<pre><code>## Loading required package: TTR</code></pre>
<pre><code>## Version 0.4-0 included new data defaults. See ?getSymbols.</code></pre>
<pre class="r"><code>library(FinTS)
library(forecast)</code></pre>
<pre><code>## This is forecast 8.12 
##   Crossvalidated is a great place to get help on forecasting issues:
##   http://stats.stackexchange.com/tags/forecasting.</code></pre>
<pre><code>## 
## Attaching package: &#39;forecast&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:FinTS&#39;:
## 
##     Acf</code></pre>
<pre class="r"><code>require(stats)
#library(stockPortfolio)
library(vars)</code></pre>
<pre><code>## Loading required package: MASS</code></pre>
<pre><code>## Loading required package: strucchange</code></pre>
<pre><code>## Loading required package: sandwich</code></pre>
<pre><code>## Loading required package: urca</code></pre>
<pre><code>## Loading required package: lmtest</code></pre>
<pre class="r"><code>library(tseries, quietly = T)
library(forecast, quietly = T)
library(fBasics)</code></pre>
<pre><code>## 
## Attaching package: &#39;fBasics&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:TTR&#39;:
## 
##     volatility</code></pre>
<pre class="r"><code>library(timsac)
library(TTR)
library(lattice)
library(foreign)
library(MASS)
require(stats4)</code></pre>
<pre><code>## Loading required package: stats4</code></pre>
<pre class="r"><code>library(KernSmooth)</code></pre>
<pre><code>## KernSmooth 2.23 loaded
## Copyright M. P. Wand 1997-2009</code></pre>
<pre class="r"><code>library(fastICA)
library(cluster)
library(leaps)
library(mgcv)</code></pre>
<pre><code>## Loading required package: nlme</code></pre>
<pre><code>## 
## Attaching package: &#39;nlme&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:forecast&#39;:
## 
##     getResponse</code></pre>
<pre><code>## This is mgcv 1.8-31. For overview type &#39;help(&quot;mgcv-package&quot;)&#39;.</code></pre>
<pre class="r"><code>library(rpart)
require(&quot;datasets&quot;)
require(graphics)
library(RColorBrewer)
library(lattice)
library(foreign)
library(KernSmooth)
library(mgcv)
library(DAAG)</code></pre>
<pre><code>## 
## Attaching package: &#39;DAAG&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:MASS&#39;:
## 
##     hills</code></pre>
<pre class="r"><code>library(&quot;TTR&quot;)
library(tis)</code></pre>
<pre><code>## 
## Attaching package: &#39;tis&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:mgcv&#39;:
## 
##     ti</code></pre>
<pre><code>## The following object is masked from &#39;package:forecast&#39;:
## 
##     easter</code></pre>
<pre><code>## The following object is masked from &#39;package:quantmod&#39;:
## 
##     Lag</code></pre>
<pre><code>## The following object is masked from &#39;package:TTR&#39;:
## 
##     lags</code></pre>
<pre><code>## The following objects are masked from &#39;package:RQuantLib&#39;:
## 
##     isBusinessDay, isHoliday</code></pre>
<pre><code>## The following objects are masked from &#39;package:timeSeries&#39;:
## 
##     description, interpNA</code></pre>
<pre><code>## The following objects are masked from &#39;package:timeDate&#39;:
## 
##     dayOfWeek, dayOfYear, isHoliday</code></pre>
<pre class="r"><code>library(&quot;forecast&quot;)
require(astsa)</code></pre>
<pre><code>## Loading required package: astsa</code></pre>
<pre><code>## 
## Attaching package: &#39;astsa&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:fBasics&#39;:
## 
##     nyse</code></pre>
<pre><code>## The following object is masked from &#39;package:forecast&#39;:
## 
##     gas</code></pre>
<pre class="r"><code>library(seasonal)</code></pre>
<pre><code>## 
## Attaching package: &#39;seasonal&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:astsa&#39;:
## 
##     unemp</code></pre>
<pre><code>## The following objects are masked from &#39;package:timeSeries&#39;:
## 
##     outlier, series</code></pre>
<pre class="r"><code>library(fpp2)</code></pre>
<pre><code>## Loading required package: ggplot2</code></pre>
<pre><code>## Loading required package: fma</code></pre>
<pre><code>## 
## Attaching package: &#39;fma&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:astsa&#39;:
## 
##     chicken, sales</code></pre>
<pre><code>## The following objects are masked from &#39;package:DAAG&#39;:
## 
##     milk, ozone</code></pre>
<pre><code>## The following objects are masked from &#39;package:MASS&#39;:
## 
##     cement, housing, petrol</code></pre>
<pre><code>## Loading required package: expsmooth</code></pre>
<pre><code>## 
## Attaching package: &#39;fpp2&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:astsa&#39;:
## 
##     oil</code></pre>
<pre class="r"><code>library(ggplot2)
library(fma)
library(seasonal)</code></pre>
<div id="i.-introduction" class="section level2">
<h2>I. Introduction</h2>
<p>Modelling and forecasting stock price is a popular and key issue for investors as well as researchers in the financial markets. In this project, our selected data is AAPL monthly adjsuted close prices from 2015 Janurary to 2019 December, which consists of 5-year stock data from Apple Inc.. We choose this stock mainly because we are interesting in AAPL stock performance and would like to fit a model and forecast AAPL monthly adjsuted close prices. Our data is in the form of historical stock prices. In this project, for the first part, we will conduct research and find a fit model and use this model to forecast the monthly AAPL adjusted close prices 25-steps ahead. In the second part, we will construct a model with a full set of seasonal dunmmies. Then, we will add some trends to improve the seasonal model. We will use this final model to forecast AAPL monthly adjusted close price for next 25 steps (months).<br />
</p>
</div>
<div id="ii.-results-answers-and-plots" class="section level2">
<h2>II. Results (answers and plots)</h2>
<p>First, we show a time-series plot of your data.<br />
</p>
<pre class="r"><code>#get the monthly data we need
getSymbols(&quot;AAPL&quot;, from = &quot;2015-01-01&quot;, to = &quot;2019-12-31&quot;,
           periodicity = &quot;monthly&quot;, curl.options = list())</code></pre>
<pre><code>## &#39;getSymbols&#39; currently uses auto.assign=TRUE by default, but will
## use auto.assign=FALSE in 0.5-0. You will still be able to use
## &#39;loadSymbols&#39; to automatically load data. getOption(&quot;getSymbols.env&quot;)
## and getOption(&quot;getSymbols.auto.assign&quot;) will still be checked for
## alternate defaults.
## 
## This message is shown once per session and may be disabled by setting 
## options(&quot;getSymbols.warning4.0&quot;=FALSE). See ?getSymbols for details.</code></pre>
<pre><code>## [1] &quot;AAPL&quot;</code></pre>
<pre class="r"><code>#create a time series object
adj.close &lt;- ts(AAPL$AAPL.Adjusted, start = 2015, frequency = 12)
#plot the time-series plot
plot(adj.close, main=&quot;AAPL Monthly Adjuested Close Price TS Plot&quot;, 
     xlab=&quot;Years&quot;, ylab = &quot;Adjusted Colse Price&quot;, 
     col  = &quot;blueviolet&quot;, ylim = c(0, 350), lwd = 2)</code></pre>
<p><img src="Project-AAPL_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>Then we plot the time-series of data with mean.<br />
</p>
<pre class="r"><code>#plot the time-series of data with mean
plot(adj.close,main=&quot;AAPL Monthly Adjusted Close Price TS Plot&quot;,
     xlab=&quot;Years&quot;, col  = &quot;blueviolet&quot;, lwd = 2)
#add the mean line
abline(h = mean(adj.close), col=&#39;red&#39;,lty=2)
#add the legend to the plot
legend(&quot;topleft&quot;, inset = 0.05, legend=c(&quot;AAPL&quot;, &quot;Mean&quot;),
       col = c(&quot;blueviolet&quot;, &quot;red&quot;), cex = 0.8, lty=1:2)</code></pre>
<p><img src="Project-AAPL_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>The graph shows the time series has an upward trend and does not have mean-reversion. The data do not have constant mean and stable variance, which suggest that the data are not covariance stationary.<br />
</p>
<p>We will plot ACF and PACF of AAPL Monthly Adjusted Close Prices.<br />
</p>
<pre class="r"><code>#plot the ACF of data
acf(AAPL$AAPL.Adjusted, main = &quot;ACF of AAPL Monthly Adjusted Close Price&quot;,
    lag.max = 25)</code></pre>
<p><img src="Project-AAPL_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<pre class="r"><code>#plot the PACF of data
pacf(AAPL$AAPL.Adjusted, main = &quot;PACF of AAPL Monthly Adjusted Close Price&quot;,
     lag.max = 25)</code></pre>
<p><img src="Project-AAPL_files/figure-html/unnamed-chunk-4-2.png" width="672" /></p>
<p>We find that in the ACF of the AAPL monthly adjusted close price, there exists a decay in the autocorrelation function, indicating non-stationarity of the data. Since the first 16 lags in ACF are beyond the range(the blue dash line), then these lags are significant, which means that the AAPL monthly adjusted close prices are correlated for the first 16 lags. For PACF, there exists a decay and a large spike of the first lag in the partial autocorrelation function.<br />
</p>
<p>We fit a linear and non-linear model to the AAPL daily adjusted close price time series.<br />
First, we fit a linear model to the series.<br />
</p>
<pre class="r"><code># Linear Fit
# create an object to store time variable 
t = seq(2015, 2020,length=length(adj.close))
# construct linear fit of the data
m1 = lm(adj.close ~ t)
# plot the original time series
plot(adj.close, ylab = &quot;AAPL Monthly Adj.Close Price&quot;, xlab=&quot;Time&quot;, 
     lwd=2, col=&#39;skyblue3&#39;, xlim=c(2015, 2020),
     main = &quot;AAPL Adj.Close and Linear Fit&quot;)
# add the fit values of the linear model
lines(t,m1$fit, col=&quot;red3&quot;, lwd=2)
#add the legend to the plot
legend(&quot;topleft&quot;, inset = 0.05, legend=c(&quot;AAPL Adj.Close&quot;, &quot;Linear Fit&quot;),
       col = c(&quot;skyblue3&quot;, &quot;red&quot;), cex = 0.8, lty=1:1)</code></pre>
<p><img src="Project-AAPL_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>Second, we fit a non-linear model to the series.<br />
</p>
<pre class="r"><code># Non-Linear Fit
# construct non-linear fit of the data
m2 = lm(adj.close ~  sin((3/4)*pi*t) + t + I(t^2))
# plot the original time series
plot(adj.close,ylab = &quot;AAPL Monthly Adj.Close Price&quot;, 
     xlab=&quot;Time&quot;, lwd=2, col=&#39;skyblue3&#39;, xlim=c(2015, 2020),
     main = &quot;AAPL Adj.Close and Non-linear Fit&quot;)
# add the fit values of the non-linear model
lines(t,m2$fit,col=&quot;red3&quot;,lwd=2)
#add the legend to the plot
legend(&quot;topleft&quot;, inset = 0.05, legend=c(&quot;AAPL Adj.Close&quot;, &quot;Non-linear Fit&quot;),
       col = c(&quot;skyblue3&quot;, &quot;red&quot;), cex = 0.8, lty=1:1)</code></pre>
<p><img src="Project-AAPL_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>First, plot the residuals and fitted values of the linear model.<br />
</p>
<pre class="r"><code>#plot the residuals and fitted values of the non-linear model
plot(m1, 1, pch = 20)</code></pre>
<p><img src="Project-AAPL_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>From the Residual vs Fitted plot, the range of residuals is large. There exists a pattern: curve up and curve down. However, there are several outliers like dot 59 and 60 in the graph. Therefore, the linear model for the AAPL daily adjusted close price is not appropriate.<br />
</p>
<p>Second, plot the residuals and fitted values of the non-linear model.<br />
</p>
<pre class="r"><code>#plot the residuals and fitted values of the non-linear model
plot(m2, 1, pch = 20)</code></pre>
<p><img src="Project-AAPL_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>From the Residual vs Fitted plot, we can see that linearity seems to hold reasonably well, as the red line is close to the dashed zero line. The residuals bounce randomly around the 0 and there is non-linear relationship between fitted values and residuals, suggesting that this model is reasonable. The residuals of the log-linear model is more stable and much smaller compared to the residual plot of the linear model. Also, the range of residuals of this model is smaller than the range of residuals of the linear model. However, there are several outliers like dot 44 and 45 in the graph. Compared to the above model, the non-linear model is better and more appropriate.<br />
</p>
<p>For each model, we plot a histogram of the residuals and discuss your observations.<br />
</p>
<p>First, we plot a histogram of the residuals of the linear model.<br />
</p>
<pre class="r"><code>#checkresiduals() produces a time plot, ACF plot and histogram of the residuals
checkresiduals(m1)</code></pre>
<p><img src="Project-AAPL_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<pre><code>## 
##  Breusch-Godfrey test for serial correlation of order up to 10
## 
## data:  Residuals
## LM test = 43.412, df = 10, p-value = 4.196e-06</code></pre>
<p>From a time plot of residuals(top), we can see that residuals do not exhibit mean-reversion. The histogram of residuals of the linear model(bottom right) has a long right tail (right-skewwed), which suggests that the residuals of the linear model are not normally distrubuted. From the ACF of residuals(bottom left), there exists an significant correlation in the first three lags in the residuals series.<br />
</p>
<p>Second, we plot a histogram of the residuals of the log-linear model.<br />
</p>
<pre class="r"><code>#checkresiduals() produces a time plot, ACF plot and histogram of the residuals
checkresiduals(m2)</code></pre>
<p><img src="Project-AAPL_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<pre><code>## 
##  Breusch-Godfrey test for serial correlation of order up to 10
## 
## data:  Residuals
## LM test = 32.103, df = 10, p-value = 0.0003849</code></pre>
<p>From a time plot of residuals (top), the range of residuals is much smaller and more close to zero compared to residuals of the linear model. From the ACF of residuals(bottom left), there exists an significant correlation at lag1 in the residuals series and the rest of the lags are within the range (blue dash line). The histogram of residuals of the non-linear model (bottom right) has a long right tail. Compared to the residuals of the linear model, the residuals of the non-linear model appear more normal.<br />
</p>
<p>For each model, we will discuss the associated diagnostics tatistics.</p>
<pre class="r"><code>#diagnostic statistics
summary(m1)</code></pre>
<pre><code>## 
## Call:
## lm(formula = adj.close ~ t)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -36.999 -17.323  -3.804   8.797  71.359 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -57264.867   4040.239  -14.17   &lt;2e-16 ***
## t               28.458      2.003   14.21   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 22.77 on 58 degrees of freedom
## Multiple R-squared:  0.7769, Adjusted R-squared:  0.773 
## F-statistic: 201.9 on 1 and 58 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Since <span class="math inline">\(R^2\)</span> is 0.7769, this indicates that 77.69% of AAPL adjusted close price can be explained by this linear model. Given <span class="math inline">\(\alpha\)</span> = 0.05, since t-value is 14.21 that is greater than 1.96, we see that the time variable is statistically significant. Since there is only 1 variable, then F distribution and t distribution are the same. Also, since all p-values are less than the 0.05 threshold, then we can conclude our model is indeed statistically significant.<br />
</p>
<pre class="r"><code>#diagnostic statistics
summary(m2)</code></pre>
<pre><code>## 
## Call:
## lm(formula = adj.close ~ sin((3/4) * pi * t) + t + I(t^2))
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -30.158  -8.212  -0.446   4.690  39.590 
## 
## Coefficients:
##                       Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)          2.535e+07  3.931e+06   6.449 2.81e-08 ***
## sin((3/4) * pi * t) -1.836e+01  2.792e+00  -6.577 1.73e-08 ***
## t                   -2.516e+04  3.897e+03  -6.457 2.72e-08 ***
## I(t^2)               6.244e+00  9.658e-01   6.465 2.64e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 14.39 on 56 degrees of freedom
## Multiple R-squared:  0.9139, Adjusted R-squared:  0.9093 
## F-statistic: 198.2 on 3 and 56 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Since R-squared is 0.9139 and it means that 91.39% of AAPL adjusted close price can be explained by this non-linear model, which shows the adjusted close price is better explained by the non-linear model. Given <span class="math inline">\(\alpha\)</span> = 5% level, since the absolute values of all t-value are greater than 1.96, we see that the <span class="math inline">\(sin((3/4) \pi t)\)</span>, t and <span class="math inline">\(t^2\)</span> are statistically significant. Also, since all p-values are less than the 0.05 threshold, then we can conclude our model is indeed statistically significant. For F-distribution, since the F-statistic (198.2) is greater than F critical value, which is approximately 3.162 and the p-value of F-statistic is less than 0.05, the data provide sufficient evidence to conclude that the non-linear model fits the data better than the model with no independent variables. So, variables <span class="math inline">\(sin((3/4) \pi t)\)</span>, t and <span class="math inline">\(t^2\)</span> are statistically significant.<br />
</p>
<p>Now, we take a look at AIC and BIC to select appropriate model</p>
<pre class="r"><code>#model selection
AIC(m1,m2)</code></pre>
<pre><code>##    df      AIC
## m1  3 549.2709
## m2  5 496.1297</code></pre>
<pre class="r"><code>BIC(m1, m2)</code></pre>
<pre><code>##    df      BIC
## m1  3 555.5539
## m2  5 506.6014</code></pre>
<p>From the tables above, since values of both AIC and BIC of the log-linear model are much smaller than those of the linear model, then both AIC and BIC select the non-linear fit as the preferred model. Therefore, the seleted models agree.<br />
</p>
<p>We forecast AAPL daily adjusted close price for next 25 steps. We forecast 25-steps ahead at 95% confidence level and h is in months.<br />
</p>
<pre class="r"><code>#create a time varaible
tn = data.frame(t = seq(from = 2020.000, to = 2022.000, by = 2/24))
#uncertainty prediction interval at 95% CI
pred.plim = predict((m2), tn, 
                    level =0.95, interval=&quot;prediction&quot;)
#confidence interval at 95% CI
pred.clim = predict((m2), tn,
                    level=0.95, interval=&quot;confidence&quot;)
#set an outside margin
#xpd = TRUE tells R that it is OK to plot outside the region 
par(mar = c(bottom = 5.1, left = 4.1, top = 3, right = 6), xpd=TRUE)
#forecast plot with uncertainty prediction interval
matplot(tn$t,cbind(pred.clim, pred.plim[,-1]),
        lty=c(1,1,1,3,3), type=&quot;l&quot;, lwd=2, 
        ylab=&quot;Predicted AAPL Adj.Closed Price&quot;,
        col = c(&quot;blue&quot;, &quot;red&quot;, &quot;skyblue3&quot;, &quot;blueviolet&quot;, &quot;green3&quot;),
        xlab=&quot;Time&quot;)
#add the legend to the plot
# horiz = FALSE tells R that I need a vertical legend
# bty = &quot;n&quot; means no outside box for the legend
#UB stands for upper bound, LB stands for lower bound
#PI stands for prediction interval
#CI stands for confidence interval
legend(&quot;topright&quot;, c(&quot;95% PI(UB)&quot;, &quot;95% CI(UB)&quot;, &quot;Fit Model&quot;, 
                     &quot;95% CI(LB)&quot;, &quot;95% PI(LB)&quot;),
       horiz = FALSE, inset=c(-0.26,0), bty = &quot;n&quot;, 
       col = c(&quot;green3&quot;, &quot;skyblue3&quot;, &quot;blue&quot;, &quot;red&quot;, &quot;blueviolet&quot;), 
       lty=c(3,1,1,1,3), cex = 0.8, title = &quot;Forecast&quot;)</code></pre>
<p><img src="Project-AAPL_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>Note that PI denotes Prediction Interval and CI denotes Confidence Interval.<br />
</p>
</div>
<div id="modeling-and-forecasting-seasonality" class="section level2">
<h2>Modeling and Forecasting Seasonality</h2>
<p>Construct and test (by looking at the diagnostic statistics) a model with a full set of seasonal dummies.</p>
<pre class="r"><code># Construct a model with a full set of seasonal dummies
fit1 = tslm(adj.close ~ season) 
# plot the seasonal model
plot(adj.close, main=&quot;Time Series Data: Seasonality&quot;, 
     col = &quot;royalblue&quot;, lwd=2)
#add a fitted values line
lines(fit1$fitted.values, col=&quot;red&quot;, lwd=2)
#add the legend to the plot
legend(&quot;topleft&quot;, inset = 0.05, 
       legend=c(&quot;AAPL Monthly Data&quot;, &quot;Seasonal Model&quot;),
       col = c(&quot;royalblue&quot;, &quot;red&quot;), cex = 0.8, lty=1:1)</code></pre>
<p><img src="Project-AAPL_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>Now, we plot the estimated seasonal factors.<br />
</p>
<pre class="r"><code>#Plot the estimated seasonal factors
plot(fit1$coef,type=&#39;l&#39;,ylab=&#39;Seasonal Factors&#39;, xlab=&quot;Season&quot;,
     lwd=2, main=&quot;Plot of Seasonal Factors&quot;)</code></pre>
<p><img src="Project-AAPL_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>Clealy, there exists low seasonal effects in Feburary. There is a peak in October and a deline in November and December. There exists an increasing trend in seasonal factors effects.<br />
</p>
<p>To improve our model, we add the trend model to the seasonal model.<br />
</p>
<pre class="r"><code>#construct a model with trend and season
fit2 &lt;- tslm(adj.close ~ season + sin((3/4)*pi*time(adj.close)) +
               time(adj.close) + I(time(adj.close)^2)) 
#plot the trending and seasona; model
plot(adj.close ,main=&quot;AAPL Monthly Adj. Close Price Full Model&quot;,
     col = &quot;royalblue&quot;, lwd=2)
#add a fitted values line
lines(fit2$fitted.values, col=&quot;red&quot;, lwd=2)
#add the legend to the plot
legend(&quot;topleft&quot;, inset = 0.05,  col = c(&quot;royalblue&quot;, &quot;red&quot;),
       legend=c(&quot;AAPL Monthly Data&quot;, &quot;Full Model&quot;), cex = 0.8, lty=1:1)</code></pre>
<p><img src="Project-AAPL_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>For the full model, we plot the respective residuals vs. fitted values.<br />
</p>
<pre class="r"><code># combine fitted values and residuals columns into one data frame
fit2_new &lt;- as.data.frame(cbind(Fitted = fitted(fit2),
                                Residuals = residuals(fit2)))
#plot the respective residuals vs. fitted values
plot(fit2_new, main = &quot;Residuals vs Fitted Values&quot;, 
     pch = 16, col = &quot;darkorange1&quot;, xlab = &quot;Fitted&quot;, ylab = &quot;Residuals&quot;)
#add a mean line
abline(h = 0, lty = 2)</code></pre>
<p><img src="Project-AAPL_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>There are several outliers in the plot. There does not exist clear pattern. The residuals bounce randomly around 0 and there is non-linear relationship between fitted values and residuals, suggesting that this model is appropriate.<br />
</p>
<p>We interpret the respective summary statistics including the error metrics of the full model.<br />
</p>
<pre class="r"><code>#show the summary statistics of the full model
summary(fit2)</code></pre>
<pre><code>## 
## Call:
## tslm(formula = adj.close ~ season + sin((3/4) * pi * time(adj.close)) + 
##     time(adj.close) + I(time(adj.close)^2))
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -31.884  -7.972  -0.897   4.243  41.074 
## 
## Coefficients:
##                                     Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept)                        2.704e+07  4.330e+06   6.244 1.35e-07
## season2                            6.313e+00  9.697e+00   0.651   0.5183
## season3                            8.999e+00  9.700e+00   0.928   0.3585
## season4                            5.800e+00  9.704e+00   0.598   0.5530
## season5                            6.587e+00  9.709e+00   0.678   0.5010
## season6                            5.718e+00  9.716e+00   0.588   0.5591
## season7                            9.086e+00  9.724e+00   0.934   0.3551
## season8                            1.473e+01  9.732e+00   1.514   0.1370
## season9                            1.433e+01  9.742e+00   1.471   0.1482
## season10                           1.981e+01  9.754e+00   2.031   0.0482
## season11                           1.247e+01  9.766e+00   1.277   0.2080
## season12                           9.286e+00  9.781e+00   0.949   0.3475
## sin((3/4) * pi * time(adj.close)) -1.775e+01  2.961e+00  -5.995 3.18e-07
## time(adj.close)                   -2.684e+04  4.293e+03  -6.252 1.32e-07
## I(time(adj.close)^2)               6.659e+00  1.064e+00   6.259 1.29e-07
##                                      
## (Intercept)                       ***
## season2                              
## season3                              
## season4                              
## season5                              
## season6                              
## season7                              
## season8                              
## season9                              
## season10                          *  
## season11                             
## season12                             
## sin((3/4) * pi * time(adj.close)) ***
## time(adj.close)                   ***
## I(time(adj.close)^2)              ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 15.33 on 45 degrees of freedom
## Multiple R-squared:  0.9215, Adjusted R-squared:  0.8971 
## F-statistic: 37.73 on 14 and 45 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Since <span class="math inline">\(R^2\)</span> is 0.9215, which means that 92.15% of the original data can be explained by the full model. Compared to the non-linear model in problem 1, the full model explains the AAPL monthly adjusted close prices better. Since the F critical value is 1.92, which is less than F-statistic(37.73), this implies there are at least one coefficient of the full model is not equal to zero. From the table, since p-values of coefficients of season10, <span class="math inline">\(sin((3/4) \pi\cdot time(adj.close))\)</span>, <span class="math inline">\(time(adj.close)\)</span> and <span class="math inline">\(I(time(adj.close)^2)\)</span> are less than the 0.05 threshold, then they are statistcally significant.<br />
</p>
<p>Now, we analyze the error metrics of our full model.<br />
</p>
<pre class="r"><code>#produce the error metrics of the full model and compare with the non-linear model
accuracy(fit2)</code></pre>
<pre><code>##                         ME     RMSE      MAE       MPE     MAPE      MASE
## Training set -1.184411e-15 13.27659 9.598611 -0.498908 6.222146 0.2888429
##                   ACF1
## Training set 0.5616792</code></pre>
<pre class="r"><code>accuracy(m2)</code></pre>
<pre><code>##                         ME     RMSE      MAE        MPE     MAPE      MASE
## Training set -1.184411e-15 13.90352 9.835545 -0.5323762 6.273262 0.2501157</code></pre>
<p>ME(Mean Error) and MASE(Mean absolute scaled error) of the full model are larger than those of the non-linear model. All error metrics except for ME and MASE of the full model are lower than those of the non-linear model, indicating that the full model performs better.<br />
</p>
<p>Then we compare mean sqaured error with the non-linear model in problem 1 and the final model.<br />
</p>
<pre class="r"><code>#install packages containing mse function
library(mltools)</code></pre>
<pre><code>## 
## Attaching package: &#39;mltools&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:PerformanceAnalytics&#39;:
## 
##     skewness</code></pre>
<pre><code>## The following object is masked from &#39;package:timeDate&#39;:
## 
##     skewness</code></pre>
<pre class="r"><code>mse(preds = fit2$fitted.values, actuals = adj.close)</code></pre>
<pre><code>## [1] 176.2679</code></pre>
<pre class="r"><code>mse(preds = m2$fitted.values, actuals = adj.close)</code></pre>
<pre><code>## [1] 193.3079</code></pre>
<p>Mean squared error for the final model is 177.8631, which is smaller than the mean sqaured error for non-linear model. Therefore, the final model is better.<br />
</p>
<p>We forecast AAPL monthly adjusted close price for next 25 steps. We forecast 25-steps ahead at 95% confidence level and h is in months.<br />
</p>
<pre class="r"><code>#uncertainty prediction interval at 95% CI
pred.plim2 = predict((fit2), tn, 
                     level =0.95, interval=&quot;prediction&quot;)</code></pre>
<pre><code>## Warning: &#39;newdata&#39; had 25 rows but variables found have 60 rows</code></pre>
<pre class="r"><code>#confidence interval at 95% CI
pred.clim2 = predict((fit2), tn,
                     level=0.95, interval=&quot;confidence&quot;)</code></pre>
<pre><code>## Warning: &#39;newdata&#39; had 25 rows but variables found have 60 rows</code></pre>
<pre class="r"><code>pred.plim3 &lt;- pred.plim2[,-1]
#
est_int &lt;- cbind(pred.clim2[1:25, ], pred.plim3[1:25, ])
#set an outside margin
#xpd = TRUE tells R that it is OK to plot outside the region 
par(mar = c(bottom = 5.1, left = 4.1, top = 3, right = 6), xpd=TRUE)
#forecast plot with uncertainty prediction interval
matplot(tn$t, est_int,
        lty=c(1,1,1,3,3), type=&quot;l&quot;, lwd=2, 
        ylab=&quot;Predicted AAPL Adj.Closed Price&quot;,
        col = c(&quot;blue&quot;, &quot;red&quot;, &quot;skyblue3&quot;, &quot;blueviolet&quot;, &quot;green3&quot;),
        xlab=&quot;Time&quot;, xlim = c(2020, 2022), ylim = c(50, 160))
#add the legend to the plot
# horiz = FALSE tells R that I need a vertical legend
# bty = &quot;n&quot; means no outside box for the legend
#UB stands for upper bound, LB stands for lower bound
#PI stands for prediction interval
#CI stands for confidence interval
legend(&quot;topright&quot;, c(&quot;95% PI(UB)&quot;, &quot;95% CI(UB)&quot;, &quot;Fit Model&quot;, 
                     &quot;95% CI(LB)&quot;, &quot;95% PI(LB)&quot;),
       horiz = FALSE, inset=c(-0.26,0), bty = &quot;n&quot;, 
       col = c(&quot;green3&quot;, &quot;skyblue3&quot;, &quot;blue&quot;, &quot;red&quot;, &quot;blueviolet&quot;), 
       lty=c(3,1,1,1,3), cex = 0.8, title = &quot;Forecast&quot;)</code></pre>
<p><img src="Project-AAPL_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
</div>
<div id="conclusions-and-future-work" class="section level2">
<h2>Conclusions and Future Work</h2>
<p>In this project, we used four different models to fit our data, and as the result shows, our final model explained our data better than the other models. We successfully forecast the trend and the seasonality of the data. However, there are something we could improve in this model. We found that the model well-fitted in the beginning of the data, and at the end the of 2018, there are some outliers. Also at the end of the 2019, the data has a significant increase. This deviate our model from the data. In the future, we believe maybe the model could improved by adding the exponential term in the trend, that will give a better trend of the model, and for the seasonality we notice there is only one significant seasonal dummy. Which indicate that for the future, we can work more on the seasonality of the model.<br />
</p>
</div>
<div id="references" class="section level2">
<h2>References</h2>
<p>George Athanasopoulos, Rob J Hyndman. (2018). Forecasting principles and practice (2nd ed., pp.69-93). Monash University, Australia.<br />
</p>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
